services:
  go_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    environment:
      NAME : go_service1
      PAYMENT_URL_DEFAULT: "http://payment-processor-default:8080/payments"
      PAYMENT_URL_FALLBACK: "http://payment-processor-fallback:8080/payments"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.40"
    #       memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true