services:
  go_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
      - "6060:6060"
    networks:
      - backend
      - payment-processor
    environment:
      NAME : go_service1
      PAYMENT_URL_DEFAULT: "http://payment-processor-default:8080/payments"
      PAYMENT_URL_FALLBACK: "http://payment-processor-fallback:8080/payments"
      PPROF_ENABLE: 0
      PPROF_ADDR: 0.0.0.0:6060
      GOMAXPROCS: 1 
      WORKERS: 2
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "125MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true