services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api1
    expose:
      - "9999"
    networks:
      - backend
      - payment-processor
    environment:
      NAME : master
      PAYMENT_URL_DEFAULT: "http://payment-processor-default:8080/payments"
      PAYMENT_URL_FALLBACK: "http://payment-processor-fallback:8080/payments"
      PPROF_ENABLE: 0
      PPROF_ADDR: 0.0.0.0:6060
      GOMAXPROCS: 1 
      WORKERS: 4
      POOLSIZE: 5000
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "125MB"

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api2
    expose:
      - "9999"
    networks:
      - backend
      - payment-processor
    environment:
      NAME : slave
      PAYMENT_URL_DEFAULT: "localhost:8001/payments"
      PAYMENT_URL_FALLBACK: "http://payment-processor-fallback:8080/payments"
      PPROF_ENABLE: 0
      PPROF_ADDR: 0.0.0.0:6060
      GOMAXPROCS: 1 
      WORKERS: 4
      POOLSIZE: 5000
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "125MB"

  haproxy:
    image: haproxy:3.2.3-alpine3.22
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true